window.PHOTOS = [
  {"title":"Diz 'n' Bird: The Beginning","artist":"Dizzy Gillespie & Charlie Parker","year":"","label":"Roost / Roulette","catalog":"SK-106","front":"https://lh3.googleusercontent.com/d/13tFHMjnjiI63kmlQJT20ADV6Zq_MHgER=w800","back":"https://lh3.googleusercontent.com/d/1LZD1TLyvUUCmyVO4u4f5PjkuQIjrVW6N=w800"},
  {"title":"Dances, Part I","artist":"Bowmar Orchestral Library","year":1965,"label":"Bowmar","catalog":"BOL 55","front":"https://lh3.googleusercontent.com/d/17PWTWlu20IMRxHc1FpdYd5XpDXJXCmyj=w800"},
  {"title":"Marches","artist":"Bowmar Orchestral Library","year":1965,"label":"Bowmar","catalog":"BOL 54","front":"https://lh3.googleusercontent.com/d/1O51dLHCHNn7GLvqXsyI8X5NtHsS-BmNJ=w800"},
  {"title":"Music, U.S.A.","artist":"Bowmar Orchestral Library","label":"Bowmar","catalog":"BOL 65","front":"https://lh3.googleusercontent.com/d/1OIoZJyy2H817Q-f0Ym94GorDW1ThR1Uf=w800"},
  {"title":"Under Many Flags","artist":"Bowmar / Noble","year":1962,"label":"Bowmar","catalog":"3162","front":"https://lh3.googleusercontent.com/d/1GAIoCaIjX_xJE9vpT4KaT-FccAD3Uxwh=w800"},
  {"title":"Live at the Village Vanguard","artist":"John Coltrane","label":"Am-Par","catalog":"A-10","front":"https://lh3.googleusercontent.com/d/1BevF5-B_oCzUz9xOc7m79qPktyahUG3-=w800","back":"https://lh3.googleusercontent.com/d/1xcSd1nctveKswkDnPte1c4fvRS1ILyPu=w800"},
  {"title":"Sketches of Spain","artist":"Miles Davis","label":"Columbia","catalog":"CS 8271","front":"https://lh3.googleusercontent.com/d/1IUTvfRZIInJ1qW0GnKFt_ZrZ4hZFWQ8c=w800","back":"https://lh3.googleusercontent.com/d/1HKe41dmDrMeZGOMSS3zK9umGlfoy6e39=w800"},
  {"title":"Night Passage","artist":"Weather Report","year":1980,"label":"CBS","catalog":"JC36793","front":"https://lh3.googleusercontent.com/d/1TBW7m44803-8v2cKCUdgRB2X5XEGYFL1=w800"},
  {"title":"The Red Back Book","artist":"Scott Joplin / New England Conservatory Ragtime Ensemble","label":"Capitol","catalog":"S-36060","front":"https://lh3.googleusercontent.com/d/1KwTbit19tZZruBWy03kZIVTbyWwWbAJv=w800"},
  {"title":"At the Five Spot","artist":"George Russell Sextet","label":"Decca","catalog":"DL9220","front":"https://lh3.googleusercontent.com/d/1CDF5BApNkvHSU8icG97m91Om3jKdBe3d=w800"},
  {"title":"The Rite of Spring","artist":"Stravinsky / Minneapolis Symphony","label":"Olympian","catalog":"MG50030","front":"https://lh3.googleusercontent.com/d/10PMXsKajnlQzihnD5hl1IKTOOKr4FYAI=w800"},
  {"title":"Symphony No. 4","artist":"Ives / Stokowski","label":"Columbia","catalog":"ML 6775","front":"https://lh3.googleusercontent.com/d/1_56q1wNIGWlhVBZ2reTVVIBJL6T0DjDz=w800"},
  {"title":"In Person Friday Night at the Blackhawk","artist":"Miles Davis","label":"Columbia","catalog":"C2L20","front":"https://lh3.googleusercontent.com/d/1g_AzIOijnKMaVDJ4udER8IdL2Mcveor9=w800"},
  {"title":"The Modern Jazz Quartet and Orchestra","artist":"Modern Jazz Quartet","label":"Atlantic","catalog":"1359","front":"https://lh3.googleusercontent.com/d/1_KyDlUEe3gtAvTsKgZUVipicEgdFj-zV=w800"},
  {"title":"Live at Monterey","artist":"Don Ellis Orchestra","label":"Pacific Jazz","catalog":"PJ-10112","front":"https://lh3.googleusercontent.com/d/1QTi5SVpSwixyvNyog_PQ67sTH37ujKZG=w800"},
  {"title":"Cookin' with the Miles Davis Quintet","artist":"Miles Davis Quintet","label":"Prestige","catalog":"7094","front":"https://lh3.googleusercontent.com/d/1yRQYIjqgPwJV2GlfgFFL5Y8r0lkvdU__=w800"},
  {"title":"Miles in the Sky","artist":"Miles Davis","label":"Columbia","catalog":"CS9628","front":"https://lh3.googleusercontent.com/d/1L_uw0Ov40fqAPKBUQQMXg-muQYbNFkpD=w800"},
  {"title":"Kronos Quartet Plays Thelonious Monk","artist":"Kronos Quartet","label":"Landmark","catalog":"LLP1505","front":"https://lh3.googleusercontent.com/d/1nGGUK4PjCCOCr8Tfh0g6lqug-Ia-B7Gj=w800"},
  {"title":"Music of Bill Evans","artist":"Kronos Quartet","label":"Landmark","catalog":"LLP1510","front":"https://lh3.googleusercontent.com/d/1z_8X_LbsYQVH3Wz-VoLT4PLeoUOrTV8L=w800"},
  {"title":"The Modern Jazz Quartet at Music Inn Vol. 2","artist":"Modern Jazz Quartet with Sonny Rollins","label":"Atlantic","catalog":"1299","front":"https://lh3.googleusercontent.com/d/1N5i_ewDsqKF2sbFc-70knT2jPsJwFM4S=w800"},
  {"title":"European Concert Vol. 1","artist":"Modern Jazz Quartet","label":"Atlantic","catalog":"1385","front":"https://lh3.googleusercontent.com/d/1LmFRINrT7yScT22RXyATOl6BE8XNB2n5=w800"},
  {"title":"Black Market","artist":"Weather Report","year":1976,"label":"CBS","catalog":"PC34099","front":"https://lh3.googleusercontent.com/d/1SIJNVGbiSIiDFU31LoI6ttLOUIaCRCr2=w800"},
  {"title":"Frampton Comes Alive","artist":"Peter Frampton","year":1976,"label":"A&M","catalog":"SP3703","front":"https://lh3.googleusercontent.com/d/1cYwyGq4orq8snQgK8JgXjQiWUG1X-yDR=w800"},
  {"title":"Getz Au Go Go","artist":"The New Stan Getz Quartet with Astrud Gilberto","label":"Verve","catalog":"V6-8600","front":"https://lh3.googleusercontent.com/d/1DjKkTRc3zi-ASlkW35cELZcVr7SefoSZ=w800"},
  {"title":"Ezz-Thetic","artist":"Lee Konitz and Miles Davis","label":"Prestige","catalog":"NJ8295","front":"https://lh3.googleusercontent.com/d/12QtkrcxKgSQEDlNJbQvmcsdMb0vf9vBs=w800"},
  {"title":"Art Blakey — The Jazz Messengers with Thelonious Monk","artist":"Art Blakey / Thelonious Monk","label":"Atlantic","catalog":"1278","front":"https://lh3.googleusercontent.com/d/1Pn4DCYOvzM6ReqJGcye2ggsw3GLGRqXw=w800"},
  {"title":"Fire, Fury and Fun","artist":"Stan Kenton and His Orchestra","label":"Creative World","catalog":"ST1073","front":"https://lh3.googleusercontent.com/d/1ZYr9gqU--ki52b7i79o_g5OjzQN0A14t=w800"},
  {"title":"Music for Wind Instruments","artist":"Georg Philipp Telemann","year":1978,"label":"Nonesuch","catalog":"H71352","front":"https://lh3.googleusercontent.com/d/1MofKZ0Usbyq6r55iaGl3dDEvF2ZY-Lzz=w800"}
];
